### ISSUE TITLE
How do you pass environment variables to the build container?

### ISSUE THREAD

**Issue by jcavalieri** [logandk/serverless-rack#33]
Hi logandk,

I need to use a different container other than the default or `lambci/lambda:build-ruby2.7` to target the aarch64-Linux architecture. So I'm using `public.ecr.aws/sam/build-ruby2.7:latest-arm64`.

I also have private gems I need to bring into the bundle. And there are two ways I know how to do that. Either by using a bundle config command or by environment variables, as explained here: https://bundler.io/man/bundle-config.1.html#CREDENTIALS-FOR-GEM-SOURCES

I've tried this, but I don't think the environment variables are being passed to the container.
```
provider:
  name: aws
  stage: ${opt:stage}
  region: ${opt:region}
  runtime: ruby2.7
  architecture: arm64
  environment:
    BUNDLE_GEMS__LONGEROUS__COM: "claudette:s00pers3krit"
```

And looking at this, it doesn't look like there is a way to do custom docker args:
https://github.com/logandk/serverless-rack/blob/7364305bcbbf7f6cc6851497069a5a4cb91936b1/index.js#L42-L48

Is what I'm trying to do possible via configuration instead of needing to create a custom image?

Thanks,
John
